version: '3'
services: 
    db:
        container_name: "postgres_db"
        image: postgres:12.0-alpine
        env_file: 
            - .env.prod
        ports: 
            - 5432:5432
    python: &python
        container_name: "django_app"            
        build: 
            context: .
            dockerfile: Dockerfile.prod
        ports: 
            - 8000:8000
        env_file: 
            - .env.prod
        command: gunicorn app.wsgi:application --bind 0.0.0.0:8000            
        depends_on: 
            - db
            - rabbitmq
            - celery_worker
    # messaging queue for celery
    rabbitmq:
        container_name: "rabbitmq_broker"
        image: rabbitmq:3.7-alpine
    celery_worker:
        <<: *python
        container_name: "celery_app"
        env_file: 
            - .env.prod
        command: celery -A app --concurrency=1 worker -l info
        ports: []

        depends_on: 
            - db
            - rabbitmq


