version: '3'
volumes: 
    static_volume:
services: 
    # db:
    #     image: postgres:12.0-alpine
    #     volumes: 
    #         - postgres_data:/var/lib/postgresql/data/
    #     env_file: 
    #         - .env.dev
    #     environment: 
    #         - POSTGRES_DB=dna_tree
    #         - POSTGRES_USER=lakshan
    #         - POSTGRES_PASSWORD=lakshan
    #     ports: 
    #         - 5432:5432
    python: &python
        build: 
            context: .
            dockerfile: Dockerfile.prod
        volumes:
            - static_volume:/usr/src/app/staticfiles
        expose:
            - 8000
        env_file: 
            - .env.prod
        command: gunicorn app.wsgi:application --bind 0.0.0.0:8000            
    # rabbitmq:
    #     image: rabbitmq:3.7-alpine
    celery_worker:
        <<: *python
        env_file: 
            - .env.prod
        command: celery -A app --concurrency=1 worker -l info
        ports: []
    
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/usr/src/app/staticfiles
        ports:
            - 1337:1337
        depends_on:
            - python
            