# Generated by Django 2.2.10 on 2020-04-06 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DNAFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, unique=True)),
                ('object_key', models.CharField(max_length=100, unique=True)),
                ('is_available', models.BooleanField(default=False)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dna_storage.Directory')),
            ],
        ),
    ]
