# Generated by Django 2.2.10 on 2020-04-12 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dna_storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dnafile',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dna_storage.Directory'),
        ),
    ]
