# Generated by Django 2.2.10 on 2020-05-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dna_storage', '0002_kmerforest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KmerForest',
        ),
    ]
