# Generated by Django 2.2.10 on 2020-05-17 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dna_storage', '0002_kmerforest'),
        ('cluster', '0006_phylogenetictreecreation_phylogenetictreeprocess_phylogenetictreeresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhylogeneticTreeUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.PhylogeneticTreeCreation')),
                ('dna_files', models.ManyToManyField(to='dna_storage.DNAFile')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.PhylogeneticTreeProcess')),
            ],
        ),
    ]
