# Generated by Django 2.2.10 on 2020-04-27 08:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dna_storage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cluster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNASimilaritiesResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhylogeneticTreeProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'LSH'), (2, 'KMER')])),
                ('status', models.IntegerField(choices=[(1, 'PROGRESS'), (2, 'SUCCESS'), (3, 'FAILED')])),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('similarities_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cluster.DNASimilaritiesResult')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhylogeneticTreeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', django.contrib.postgres.fields.jsonb.JSONField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.PhylogeneticTreeProcess')),
            ],
        ),
        migrations.CreateModel(
            name='MatrixProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'LSH'), (2, 'KMER')])),
                ('status', models.IntegerField(choices=[(1, 'PROGRESS'), (2, 'SUCCESS'), (3, 'FAILED')])),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('dna_files', models.ManyToManyField(to='dna_storage.DNAFile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KMerForestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_locaion', models.CharField(max_length=250)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.MatrixProcess')),
            ],
        ),
        migrations.AddField(
            model_name='dnasimilaritiesresult',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.MatrixProcess'),
        ),
    ]
