# Generated by Django 2.2.10 on 2020-04-14 20:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_process_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', django.contrib.postgres.fields.jsonb.JSONField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.Process')),
            ],
        ),
    ]
