# Generated by Django 2.2.10 on 2020-05-17 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0003_auto_20200427_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phylogenetictreeresult',
            name='process',
        ),
        migrations.DeleteModel(
            name='PhylogeneticTreeProcess',
        ),
        migrations.DeleteModel(
            name='PhylogeneticTreeResult',
        ),
    ]
