# Generated by Django 2.2.10 on 2020-05-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0004_auto_20200517_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KMerForestResult',
        ),
    ]
