# Generated by Django 2.2.10 on 2020-05-17 16:33

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cluster', '0005_delete_kmerforestresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhylogeneticTreeProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, 'TREE_CREATION'), (2, 'TREE_UPDATION')])),
                ('status', models.IntegerField(choices=[(1, 'PROGRESS'), (2, 'SUCCESS'), (3, 'FAILED')])),
                ('crated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhylogeneticTreeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', django.contrib.postgres.fields.jsonb.JSONField()),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.PhylogeneticTreeProcess')),
            ],
        ),
        migrations.CreateModel(
            name='PhylogeneticTreeCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'LSH'), (2, 'KMER')])),
                ('matrix_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.MatrixProcess')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.PhylogeneticTreeProcess')),
            ],
        ),
    ]
